version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PORT=8000
      - MAX_CONCURRENT_REQUESTS=10
      - MAX_QUEUE_SIZE=100
      - LLM_TIMEOUT_MS=30000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
